import type { WebsiteContent } from "@/lib/websiteContent";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// theme.{primaryColor,backgroundColor,textColor} go straight into a <style>
// block below with no other escaping — WebsiteContentSchema already
// enforces this hex format, but re-checking here means a row saved under an
// older, looser schema (or any future caller) can't break out of the CSS
// context, which was a stored-XSS vector reachable from the theme editor's
// free-text color input.
function sanitizeHexColor(value: string, fallback: string): string {
  return /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3}){0,2}$/.test(value) ? value : fallback;
}

// The AI picks primaryColor freely (any hex, any lightness) — a hardcoded
// white button label would go invisible on a light accent color (e.g.
// pastel yellow), which is exactly the "white-on-white CTA" failure mode.
// Computing readable button text from the accent's actual luminance
// guarantees WCAG-safe contrast regardless of what the AI chose, for free
// (no extra tokens, applies to every generated page).
function readableTextColor(hex: string): "#ffffff" | "#0a0a0a" {
  const full = hex.length === 4 ? hex.slice(1).split("").map((c) => c + c).join("") : hex.slice(1, 7);
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16) / 255);
  const toLinear = (c: number) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  const luminance = 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
  return luminance > 0.55 ? "#0a0a0a" : "#ffffff";
}

/** Turns a YouTube/Vimeo watch/share URL into its embeddable iframe src — accepts whatever format a client pastes. */
function toEmbedUrl(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname.includes("youtu.be")) {
      return `https://www.youtube.com/embed/${u.pathname.slice(1)}`;
    }
    if (u.hostname.includes("youtube.com")) {
      const id = u.searchParams.get("v");
      if (id) return `https://www.youtube.com/embed/${id}`;
      if (u.pathname.startsWith("/embed/")) return url;
    }
    if (u.hostname.includes("vimeo.com")) {
      const id = u.pathname.split("/").filter(Boolean).pop();
      if (id) return `https://player.vimeo.com/video/${id}`;
    }
    return null;
  } catch {
    return null;
  }
}

function fontLink(fonts: string[]): string {
  const families = fonts.map((f) => `family=${encodeURIComponent(f)}:wght@400;600;700`).join("&");
  return `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?${families}&display=swap" rel="stylesheet">`;
}

export function renderWebsiteHtml(
  content: WebsiteContent,
  // trackingBasePath: "/sitio/{slug}" when served at that path, or "" when
  // served at the root of a connected custom domain (see proxy.ts) — either
  // way CTAs route through "{trackingBasePath}/ir?label=..." so a click is
  // logged (see app/sitio/[slug]/ir/route.ts) before redirecting to the
  // real target, which is resolved server-side there (never trusts a
  // client-supplied URL, so this can't be abused as an open redirect).
  // preview: true when this render is for the dashboard's own "Vista
  // previa" iframe (see WebsiteEditor.tsx), not a real visitor — carried
  // through every tracked link/form on the page so the owner opening their
  // own editor, or saving a change and triggering a preview reload, never
  // inflates their own view/click/lead counts. See the ?preview=1 check in
  // route.ts, ir/route.ts and registro/route.ts.
  // eyebrow: small label above the hero heading (e.g. "Coaching /
  // consultoría") — derived server-side from the business's industry, not
  // generated by the AI, so it costs nothing extra. heroImageUrl: this
  // business's own most-recently-uploaded photo (see AgentMedia), if any —
  // deliberately NOT a stock photo, so every client's page shows something
  // real and unique to them instead of the same generic photo repeated
  // across every business in an industry; the hero just renders text-only
  // (like funnelslabs.app's own, image-free hero) when they haven't
  // uploaded one yet.
  ctx: {
    businessName: string;
    whatsappNumber: string;
    trackingBasePath: string;
    leadSubmitted?: boolean;
    preview?: boolean;
    eyebrow?: string | null;
    heroImageUrl?: string | null;
  },
): string {
  const embedUrl = content.videoUrl ? toEmbedUrl(content.videoUrl) : null;
  const previewParam = ctx.preview ? "&preview=1" : "";
  const trackedHref = (label: string) => `${ctx.trackingBasePath}/ir?label=${encodeURIComponent(label)}${previewParam}`;
  const registroAction = `${ctx.trackingBasePath}/registro${ctx.preview ? "?preview=1" : ""}`;
  const fonts = Array.from(new Set([content.theme.headingFont, content.theme.bodyFont]));
  const primary = sanitizeHexColor(content.theme.primaryColor, "#1f6feb");
  const btnText = readableTextColor(primary);
  const eyebrow = ctx.eyebrow?.trim() || "Atención por WhatsApp";
  const heroImageUrl = ctx.heroImageUrl?.trim() || null;

  const offerHtml = content.offer.items
    .map(
      (s) => `
      <div class="card">
        <h3>${escapeHtml(s.title)}</h3>
        <p>${escapeHtml(s.description)}</p>
      </div>`,
    )
    .join("");

  const objectionsHtml = content.objections.items
    .map(
      (o) => `
      <div class="objection-card">
        <p class="objection-q">${escapeHtml(o.question)}</p>
        <p class="objection-a">${escapeHtml(o.answer)}</p>
      </div>`,
    )
    .join("");

  return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(ctx.businessName)}</title>
${fontLink(fonts)}
<style>
  :root {
    --primary: ${primary};
    --btn-text: ${btnText};
    --bg: ${sanitizeHexColor(content.theme.backgroundColor, "#ffffff")};
    --text: ${sanitizeHexColor(content.theme.textColor, "#0a0a0a")};
    --heading-font: "${content.theme.headingFont}", sans-serif;
    --body-font: "${content.theme.bodyFont}", sans-serif;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text); font-family: var(--body-font); line-height: 1.65; -webkit-font-smoothing: antialiased; }
  h1, h2, h3 { font-family: var(--heading-font); line-height: 1.15; letter-spacing: -0.01em; margin: 0 0 0.5em; text-wrap: balance; }
  h1 { font-size: clamp(30px, 5vw, 50px); }
  h2 { font-size: clamp(22px, 3.5vw, 32px); }
  p { margin: 0 0 1em; }
  a { -webkit-tap-highlight-color: transparent; }
  a:focus-visible, button:focus-visible, input:focus-visible, textarea:focus-visible { outline: 2px solid var(--primary); outline-offset: 2px; }
  .wrap { max-width: 1080px; margin: 0 auto; padding: 0 24px; }
  header.top { padding: 20px 0; }
  header.top .wrap { display: flex; align-items: center; justify-content: space-between; }
  .brand { font-family: var(--heading-font); font-weight: 700; font-size: 18px; letter-spacing: -0.01em; }
  .btn { display: inline-block; background: var(--primary); color: var(--btn-text); padding: 14px 28px; border-radius: 999px; text-decoration: none; font-weight: 600; font-family: var(--body-font); transition: transform 0.15s ease, box-shadow 0.15s ease, opacity 0.15s ease; box-shadow: 0 1px 2px color-mix(in srgb, var(--primary) 25%, transparent); }
  .btn:hover { opacity: 0.92; transform: translateY(-1px); box-shadow: 0 6px 16px color-mix(in srgb, var(--primary) 30%, transparent); }
  .btn:active { transform: translateY(0); }
  section { padding: 64px 0; }
  section:nth-of-type(even):not(.hero):not(.lead-section) { background: color-mix(in srgb, var(--bg) 96%, var(--text)); }
  .eyebrow { margin: 0 0 14px; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.14em; color: var(--primary); }
  .kicker { margin: 0 0 10px; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: color-mix(in srgb, var(--text) 55%, transparent); }
  .hero { position: relative; overflow: hidden; padding: 96px 0 76px; }
  .hero-grid-bg {
    position: absolute; inset: 0; z-index: 0; pointer-events: none; opacity: 0.5;
    background-image:
      linear-gradient(color-mix(in srgb, var(--text) 10%, transparent) 1px, transparent 1px),
      linear-gradient(90deg, color-mix(in srgb, var(--text) 10%, transparent) 1px, transparent 1px);
    background-size: 40px 40px;
  }
  .hero-inner { position: relative; z-index: 1; }
  .hero-centered { max-width: 720px; margin: 0 auto; text-align: center; }
  .hero-with-image { display: grid; grid-template-columns: 1.1fr 1fr; gap: 48px; align-items: center; text-align: left; }
  .hero .subheading { font-size: 19px; opacity: 0.78; max-width: 58ch; }
  .hero-centered .subheading { margin-inline: auto; }
  .hero .btn { margin-top: 8px; }
  .hero-media img { display: block; width: 100%; height: auto; border-radius: 20px; border: 1px solid color-mix(in srgb, var(--text) 10%, transparent); box-shadow: 0 24px 60px -20px color-mix(in srgb, var(--text) 35%, transparent); }
  h2 { margin-bottom: 0.7em; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 20px; margin-top: 24px; }
  .card {
    border: 1px solid color-mix(in srgb, var(--text) 10%, transparent); border-radius: 16px; padding: 28px;
    background: radial-gradient(120% 140% at 100% 0%, color-mix(in srgb, var(--primary) 8%, transparent), transparent 55%), var(--bg);
    box-shadow: 0 1px 3px color-mix(in srgb, var(--text) 6%, transparent);
    transition: border-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease;
  }
  .card:hover { border-color: color-mix(in srgb, var(--primary) 35%, transparent); transform: translateY(-2px); box-shadow: 0 10px 24px -8px color-mix(in srgb, var(--primary) 25%, transparent); }
  .card h3 { font-size: 18px; }
  .card p { opacity: 0.8; margin-bottom: 0; }
  .video-wrap { position: relative; padding-top: 56.25%; border-radius: 14px; overflow: hidden; margin-top: 16px; box-shadow: 0 8px 24px color-mix(in srgb, var(--text) 12%, transparent); }
  .video-wrap iframe { position: absolute; inset: 0; width: 100%; height: 100%; border: 0; }
  .objection-card { border-left: 3px solid var(--primary); padding: 4px 0 4px 20px; }
  .objection-q { font-weight: 600; margin-bottom: 0.3em; }
  .objection-a { opacity: 0.8; margin: 0; }
  .lead-section .wrap { max-width: 480px; text-align: center; }
  .lead-form { display: flex; flex-direction: column; gap: 10px; margin-top: 20px; text-align: left; }
  .lead-form input, .lead-form textarea { font: inherit; font-family: var(--body-font); padding: 12px 14px; border-radius: 8px; border: 1px solid color-mix(in srgb, var(--text) 25%, transparent); background: color-mix(in srgb, var(--bg) 92%, var(--text)); color: var(--text); }
  .lead-form input::placeholder, .lead-form textarea::placeholder { color: color-mix(in srgb, var(--text) 55%, transparent); }
  .lead-form textarea { resize: vertical; }
  .lead-form button { align-self: center; border: none; cursor: pointer; }
  .lead-thanks { font-weight: 600; color: var(--primary); }
  footer { padding: 40px 0; text-align: center; opacity: 0.6; font-size: 13px; }
  footer a { color: inherit; }
  @media (max-width: 760px) { .hero-with-image { grid-template-columns: 1fr; text-align: center; } .hero-with-image .subheading { margin-inline: auto; } .hero-with-image .hero-media { order: -1; } }
  @media (max-width: 600px) { .wrap { padding: 0 16px; } section { padding: 44px 0; } .hero { padding: 56px 0 44px; } }
</style>
</head>
<body>
  <header class="top">
    <div class="wrap">
      <span class="brand">${escapeHtml(ctx.businessName)}</span>
      <a class="btn" href="${escapeHtml(trackedHref("header"))}" target="_blank" rel="noopener noreferrer" style="padding:10px 20px;">WhatsApp</a>
    </div>
  </header>

  <section class="hero">
    <div class="hero-grid-bg" aria-hidden="true"></div>
    <div class="wrap hero-inner ${heroImageUrl ? "hero-with-image" : "hero-centered"}">
      <div class="hero-copy">
        <p class="eyebrow">${escapeHtml(eyebrow)}</p>
        <h1>${escapeHtml(content.hero.heading)}</h1>
        <p class="subheading">${escapeHtml(content.hero.subheading)}</p>
        <a class="btn" href="${escapeHtml(trackedHref("hero"))}" target="_blank" rel="noopener noreferrer">${escapeHtml(content.hero.ctaLabel)}</a>
      </div>
      ${
        heroImageUrl
          ? `<div class="hero-media"><img src="${escapeHtml(heroImageUrl)}" alt="${escapeHtml(ctx.businessName)}" loading="eager"></div>`
          : ""
      }
    </div>
  </section>

  ${
    embedUrl
      ? `<section>
    <div class="wrap">
      <div class="video-wrap"><iframe src="${escapeHtml(embedUrl)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
    </div>
  </section>`
      : ""
  }

  <section>
    <div class="wrap">
      <p class="kicker">Lo que ofrecemos</p>
      <h2>${escapeHtml(content.offer.heading)}</h2>
      <div class="grid">${offerHtml}</div>
    </div>
  </section>

  <section>
    <div class="wrap">
      <p class="kicker">Antes de escribirnos</p>
      <h2>${escapeHtml(content.objections.heading)}</h2>
      <div class="grid">${objectionsHtml}</div>
    </div>
  </section>

  <section>
    <div class="wrap" style="text-align:center;">
      <h2>${escapeHtml(content.contact.heading)}</h2>
      <p>${escapeHtml(content.contact.body)}</p>
      <a class="btn" href="${escapeHtml(trackedHref("contact"))}" target="_blank" rel="noopener noreferrer">${escapeHtml(content.hero.ctaLabel)}</a>
    </div>
  </section>

  <section class="lead-section">
    <div class="wrap">
      <h2>Déjanos tus datos</h2>
      ${
        ctx.leadSubmitted
          ? `<p class="lead-thanks">¡Listo! Ya tenemos tus datos, te contactamos muy pronto.</p>`
          : `<p>Te escribimos apenas los recibamos.</p>
      <form class="lead-form" method="POST" action="${escapeHtml(registroAction)}">
        <input type="text" name="name" placeholder="Tu nombre" maxlength="120" required>
        <input type="text" name="contact" placeholder="Tu WhatsApp o teléfono" maxlength="120" required>
        <textarea name="message" placeholder="Cuéntanos qué necesitas (opcional)" rows="2" maxlength="500"></textarea>
        <button class="btn" type="submit">Enviar</button>
      </form>`
      }
    </div>
  </section>

  <footer>
    <div class="wrap">Sitio creado con IA · <a href="https://funnelslabs.app" target="_blank" rel="noopener noreferrer">Funnels Labs</a></div>
  </footer>
</body>
</html>`;
}
